ENVIRONMENT: "local"
VERSION: "local"
LOG_LEVEL: "debug"
POD_IP: "127.0.0.1"
SERVER:
  ADDR: "127.0.0.1:8099"
  WRITE_TIMEOUT: 15
  READ_TIMEOUT: 15
  IDLE_TIMEOUT: 60
DATABASE:
  DATABASE_SERVER: "localhost"
  DATABASE_PORT: 54329
  DATABASE_NAME: "one-db-local"
  DATABASE_USER: "one"
  DATABASE_PASSWORD: "one"
  DATABASE_LOG_LEVEL: "Info"
  DATABASE_SSL_MODE: "prefer"
KAFKA_CONFIG:
  COMMON:
    BOOTSTRAP_SERVERS:
      - "localhost:9092"
    GROUP_ID: "one-local"
    AUTO_OFFSET_RESET: "earliest"
  ONE_REQUEST_TOPIC:
    NAME: "one-request-local"
    PARTITION_COUNT: 1
    REPLICA_COUNT: 1

