SERVER:
  ADDR: "127.0.0.1:8080"
  WRITE_TIMEOUT: 15
  READ_TIMEOUT: 15
  IDLE_TIMEOUT: 60
DATABASE:
  DATABASE_SERVER: "localhost"
  DATABASE_PORT: 54321
  DATABASE_NAME: "one-db-local"
  DATABASE_USER: "one"
  DATABASE_PASSWORD: "one"
  DATABASE_LOG_LEVEL: "Info"
  DATABASE_SSL_MODE: "prefer"

