version: '3.5'

services:
  kafka-server:
    image: bitnami/kafka:latest
    restart: unless-stopped
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper-server:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_CFG_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: INSIDE://kafka-server:29092,OUTSIDE://localhost:9092
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CFG_MESSAGE_MAX_BYTES: 2000024
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      - zookeeper-server
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper-server:2181"]
      start_period: 20s
      interval: 15s
      timeout: 15s
      retries: 5
    networks:
      - cruncan-network

  zookeeper-server:
    image: bitnami/zookeeper:latest
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/bitnami/zookeeper
    networks:
      - cruncan-network

volumes:
  kafka-data:
  zookeeper-data:

networks:
  cruncan-network:
    external: true