version: '3.5'

services:
  one-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: one
      POSTGRES_PASSWORD: one
      POSTGRES_DB: one-db-local
    ports:
      - "54329:5432"
    volumes:
      - one-db-data:/var/lib/postgresql/data
    networks:
      - cruncan-network

  migration:
    image: migrate/migrate:latest
    entrypoint: migrate -verbose -path=/migrations  -database "postgres://one:one@one-db:5432/one-db-local?sslmode=disable" up
    volumes:
      - ./database/migrations:/migrations
    depends_on:
      - one-db
    networks:
      - cruncan-network

volumes:
  one-db-data:

networks:
  cruncan-network:
    external: true
